// <auto-generated />
using BE_PruebaTecnica.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BE_PruebaTecnica.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    [Migration("20240923041535_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BE_PruebaTecnica.EfCore.Empresa", b =>
                {
                    b.Property<int>("nit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nit"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("productosCodigo")
                        .HasColumnType("integer");

                    b.HasKey("nit");

                    b.HasIndex("productosCodigo");

                    b.ToTable("tb_empresa");
                });

            modelBuilder.Entity("BE_PruebaTecnica.EfCore.Producto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Caracteristicas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Codigo");

                    b.ToTable("tb_producto");
                });

            modelBuilder.Entity("BE_PruebaTecnica.EfCore.Empresa", b =>
                {
                    b.HasOne("BE_PruebaTecnica.EfCore.Producto", "productos")
                        .WithMany()
                        .HasForeignKey("productosCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
